logging:
    level:
        ROOT: INFO
spring:
    application:
      name: rest-repository
    data:
      elasticsearch:
        cluster-nodes: localhost:9300
---
spring:
    profiles: docker
    data:
      elasticsearch:
        cluster-nodes: elasticsearch:9300
---
server:
  port: ${service.rest-repository.port}
spring:
  profiles: debug